### ISSUE TITLE
Gateway local API returns 401 when endnode application is different from gateway application.

### ISSUE THREAD

**Issue by FGtatsuroWork** [KiiPlatform/gateway-agent#106]
REST access: /development_jp/apps/e364df17/gateway/onboarding (development_jp: custom site)
token: from /development_jp/token, and following config.

```
master_app:
  site: development_jp
  app_id: a6d18eef
  app_key: 9b0c37d275dab4aa7818c76c296b0b45
```

Error point is here.
https://github.com/KiiPlatform/gateway-agent/blob/develop/internal/local/operation.go#L181
